export const SET_TITLE = 'SET_TITLE';
export const SET_SELECT = 'SET_SELECT';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const VALIDATE_WORKOUT_TITLE = 'VALIDATE_WORKOUT_TITLE';

export const AUTHORIZE_USER = 'AUTHORIZE_USER';