export const SET_TITLE = 'SET_TITLE';
export const SET_SELECT = 'SET_SELECT';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const SIGNUP_REDIRECT = 'SIGNUP_REDIRECT';

export const POST_ANON_START = 'POST_ANON_START';
export const POST_ANON_SUCCESS = 'POST_ANON_SUCCESS';
export const POST_ANON_FAILURE = 'POST_ANON_FAILURE';

export const AUTHORIZE_USER = 'AUTHORIZE_USER';